stages:
  # - test
  - build
  - deploy

image: $DOCKER_REGISTRY_PULL/vmware-handler-builder

services:
  - name: $DOCKER_REGISTRY_PULL/deputy-package-server-repository-combo
    alias: deputy-package-server-combo
  - name: $DOCKER_REGISTRY_PULL/featurer-redis-server
    alias: featurer-redis-server

variables:
  REPO_NAME: code.ocr.cr14.net/open-cyber-range/public/vmware-node-deployer
  GIT_SUBMODULE_STRATEGY: normal
  FF_NETWORK_PER_BUILD: "true"


before_script:
  - mkdir -p "$GOPATH/src/$(dirname $REPO_NAME)"
  - ln -svf "$CI_PROJECT_DIR" "$GOPATH/src/$REPO_NAME"
  - cd "$GOPATH/src/$REPO_NAME"

# test:
#   stage: test
#   script:
#     - TEST_VMWARE_USER=$OCR_TEST_VMWARE_USER 
#       TEST_VMWARE_PASSWORD=$OCR_TEST_VMWARE_PASSWORD 
#       TEST_VMWARE_HOSTNAME=$OCR_TEST_VMWARE_HOSTNAME 
#       TEST_VMWARE_TEMPLATE_FOLDER_PATH=$OCR_TEST_VMWARE_TEMPLATE_FOLDER_PATH 
#       TEST_VMWARE_RESOURCE_POOL_PATH=$OCR_TEST_VMWARE_RESOURCE_POOL_PATH 
#       TEST_VMWARE_EXERCISE_ROOT_PATH=$OCR_TEST_VMWARE_EXERCISE_ROOT_PATH 
#       TEST_NSXT_API=$OCR_TEST_NSXT_API
#       TEST_NSXT_AUTH=$OCR_TEST_NSXT_AUTH
#       TEST_NSXT_TRANSPORT_ZONE_NAME=$OCR_TEST_NSXT_TRANSPORT_ZONE_NAME
#       TEST_VMWARE_DATASTORE_PATH=$OCR_TEST_VMWARE_DATASTORE_PATH
#       TEST_REDIS_ADDRESS=$OCR_TEST_REDIS_ADDRESS
#       TEST_REDIS_PASSWORD=$OCR_TEST_REDIS_PASSWORD
#       make test
#   only:
#     - develop
#     - master
#     - merge_requests

#build-and-upload-x86-64bit-linux-release-for-ranger-vmware-handlers:
#  stage: build
  # needs: ["test"]
#  script:
#    - make build-deb
#    - DEB_FILE=$(find ../ -maxdepth 1 -type f -name "*.deb")
#    - 'curl --fail -u $OCR_DEPLOYMENT_USER:$OCR_DEPLOYMENT_PASSWORD -X POST -H "Content-Type: multipart/form-data" --data-binary "@$DEB_FILE" $OCR_APT_REPOSITORY'
#  only:
#    - master

staging:
  stage: deploy
  variables:
    RANGER_VMWARE_HANLDER: "1"
  trigger:
    open-cyber-range/internal/support-docker-images
  only:
    - master

sync-to-github:
  stage: deploy
  image: $DOCKER_REGISTRY_PULL/ocr-base-deployment-image
  before_script:
    - apt update && apt install -y git
  script:
    - git remote remove github || echo "No repo found"
    - git remote add github https://mannyfred:$MANFRED_GITHUB_TOKEN@github.com/Open-Cyber-Range/VMWare-Handler.git
    - git checkout master
    - git pull --rebase origin master
    - git push github master:main --force
  only:
    - master


