/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsx_t_openapi

// Livetrace action configuration
type PolicyLiveTraceActionConfig struct {
	PktcapConfig *LiveTracePacketGranularActionConfig `json:"pktcap_config,omitempty"`
	TraceConfig *LiveTracePacketGranularActionConfig `json:"trace_config,omitempty"`
}
