/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsx_t_openapi

// Contain optional configuration for deployment. 
type AdvanceServiceConfig struct {
	// Filename of uploaded Kubernetes tools
	KubectlTool string `json:"kubectl_tool,omitempty"`
	// FQDN to access kafka messaging service pod.
	MessagingServiceName string `json:"messaging_service_name,omitempty"`
	// FQDN to access deployment pod.
	ServiceName string `json:"service_name,omitempty"`
}
