/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsx_t_openapi

// Optional API Request Parameter to be used in HAPI.
type PolicyRequestParameter struct {
	// The type of this request parameter.
	ResourceType string `json:"resource_type"`
}
