version: "3.7"

services:
  go-development:
    image: nexus.ocr.cr14.net:8003/go-development:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - ./development-configs/deputy-cli-configuration.toml:/home/vscode/.deputy/configuration.toml
    user: vscode
    ports:
      - 8080:8080

  deputy-package-server:
    image: nexus.ocr.cr14.net:8003/deputy-package-server:latest
    volumes:
      - ./deputy-packages:/var/opt/deputy/deputy-package-server/package
      - ./deputy-repository:/var/opt/deputy/deputy-package-server/repository
      - ./development-configs/deputy-package-server-configuration.yml:/etc/opt/deputy/deputy-package-server/config.yml

    environment:
      - RUST_LOG=debug

  vmware-handler-mariadb:
    image: nexus.ocr.cr14.net:8003/mariadb:10.7
    ports:
      - "3308:3308"
    volumes:
      - ~/apps/handlers-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_DATABASE: handlers
      MYSQL_TCP_PORT: 3308


  featurer-redis-server:
    image: nexus.ocr.cr14.net:8003/featurer-redis-server
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6380:6380
    volumes:
      - ./development-configs/redis-configuration.conf:/etc/redis/redis.conf
