version: "3"

services:
  go-development:
    image: nexus.ocr.cr14.net:8003/go-development:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - ./configs/deputy-cli-configuration.toml:/home/vscode/.deputy/configuration.toml
    user: vscode
    ports:
      - 8080:8080

  deputy-package-server:
    image: nexus.ocr.cr14.net:8003/deputy-package-server:latest
    volumes:
      - ./deputy-packages:/var/opt/deputy/deputy-package-server/package
      - ./deputy-repository:/var/opt/deputy/deputy-package-server/repository
    environment:
      - RUST_LOG=debug

  index-repository:
    image: nexus.ocr.cr14.net:8003/deputy-repository-server
    volumes:
      - ./deputy-repository/.git:/srv/git/index.git
    ports:
      - 8081:80

  featurer-redis-server:
    image: nexus.ocr.cr14.net:8003/featurer-redis-server
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6380:6380
    volumes:
      - ./configs/redis-configuration.conf:/etc/redis/redis.conf
