// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: deployer-grpc/deployer-grpc.proto

package deployer_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reply_Status int32

const (
	Reply_OK    Reply_Status = 0
	Reply_ERROR Reply_Status = 1
)

// Enum value maps for Reply_Status.
var (
	Reply_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Reply_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Reply_Status) Enum() *Reply_Status {
	p := new(Reply_Status)
	*p = x
	return p
}

func (x Reply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_deployer_grpc_deployer_grpc_proto_enumTypes[0].Descriptor()
}

func (Reply_Status) Type() protoreflect.EnumType {
	return &file_deployer_grpc_deployer_grpc_proto_enumTypes[0]
}

func (x Reply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reply_Status.Descriptor instead.
func (Reply_Status) EnumDescriptor() ([]byte, []int) {
	return file_deployer_grpc_deployer_grpc_proto_rawDescGZIP(), []int{1, 0}
}

// The request message containing the user's name.
type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_deployer_grpc_deployer_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  Reply_Status `protobuf:"varint,1,opt,name=status,proto3,enum=Reply_Status" json:"status,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_deployer_grpc_deployer_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetStatus() Reply_Status {
	if x != nil {
		return x.Status
	}
	return Reply_OK
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The response message containing the greetings
type EntityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EntityId) Reset() {
	*x = EntityId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityId) ProtoMessage() {}

func (x *EntityId) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_grpc_deployer_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityId.ProtoReflect.Descriptor instead.
func (*EntityId) Descriptor() ([]byte, []int) {
	return file_deployer_grpc_deployer_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *EntityId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_deployer_grpc_deployer_grpc_proto protoreflect.FileDescriptor

var file_deployer_grpc_deployer_grpc_proto_rawDesc = []byte{
	0x0a, 0x21, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x65, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x32, 0x47, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x19, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x05, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x1a, 0x06, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x1d, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x09, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x1a, 0x06, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x40, 0x5a, 0x3e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x2d, 0x63,
	0x79, 0x62, 0x65, 0x72, 0x2d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x76, 0x6d, 0x77, 0x61, 0x72,
	0x65, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2f,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_deployer_grpc_deployer_grpc_proto_rawDescOnce sync.Once
	file_deployer_grpc_deployer_grpc_proto_rawDescData = file_deployer_grpc_deployer_grpc_proto_rawDesc
)

func file_deployer_grpc_deployer_grpc_proto_rawDescGZIP() []byte {
	file_deployer_grpc_deployer_grpc_proto_rawDescOnce.Do(func() {
		file_deployer_grpc_deployer_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_deployer_grpc_deployer_grpc_proto_rawDescData)
	})
	return file_deployer_grpc_deployer_grpc_proto_rawDescData
}

var file_deployer_grpc_deployer_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deployer_grpc_deployer_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deployer_grpc_deployer_grpc_proto_goTypes = []interface{}{
	(Reply_Status)(0), // 0: Reply.Status
	(*Node)(nil),      // 1: Node
	(*Reply)(nil),     // 2: Reply
	(*EntityId)(nil),  // 3: EntityId
}
var file_deployer_grpc_deployer_grpc_proto_depIdxs = []int32{
	0, // 0: Reply.status:type_name -> Reply.Status
	1, // 1: NodeService.Create:input_type -> Node
	3, // 2: NodeService.Delete:input_type -> EntityId
	2, // 3: NodeService.Create:output_type -> Reply
	2, // 4: NodeService.Delete:output_type -> Reply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deployer_grpc_deployer_grpc_proto_init() }
func file_deployer_grpc_deployer_grpc_proto_init() {
	if File_deployer_grpc_deployer_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deployer_grpc_deployer_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deployer_grpc_deployer_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deployer_grpc_deployer_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deployer_grpc_deployer_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_grpc_deployer_grpc_proto_goTypes,
		DependencyIndexes: file_deployer_grpc_deployer_grpc_proto_depIdxs,
		EnumInfos:         file_deployer_grpc_deployer_grpc_proto_enumTypes,
		MessageInfos:      file_deployer_grpc_deployer_grpc_proto_msgTypes,
	}.Build()
	File_deployer_grpc_deployer_grpc_proto = out.File
	file_deployer_grpc_deployer_grpc_proto_rawDesc = nil
	file_deployer_grpc_deployer_grpc_proto_goTypes = nil
	file_deployer_grpc_deployer_grpc_proto_depIdxs = nil
}
